version: '2.4'

services:

  node_backend:
    container_name: node_backend
    build:
      dockerfile: Dockerfile
      context: ./backend
    ports:
      - '3001:3001'

    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5432
      - DATABASE=onlydogs
      - HOST=localhost
      - POSTGRES_HOST=db
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./backend:/usr/src/app:cached
    depends_on:
      - db

  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PORT=5432
      - DATABASE=onlydogs
      - HOST=localhost
    volumes:
      - db-data:/var/lib/postgresql/data:delegated

volumes:
  db-data:
